name: Build Docker on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-telegram:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push CatMessenger.Telegram image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CatMessenger.Telegram/Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/catmessenger-telegram:latest

  build-matrix:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and push CatMessenger.Matrix image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CatMessenger.Matrix/Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/catmessenger-matrix:latest